/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO;

import BDATOS.CONEXIONJDBC;
import BDATOS.USUARIOCONEXION;
import DOMINIO.mdEMPLEADO;
import DOMINIO.mdUSUARIO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Iris Damian
 */
public class INGRESO extends javax.swing.JFrame {

    /**
     * Creates new form INGRESO
     */
    public INGRESO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldN = new javax.swing.JTextField();
        jTextFieldE = new javax.swing.JTextField();
        jTextFieldF = new javax.swing.JTextField();
        jTextFieldM = new javax.swing.JTextField();
        jButtonI = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonME = new javax.swing.JButton();
        jButtonBO = new javax.swing.JButton();
        jButtonGT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArearespuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 153));
        jLabel1.setText("INGRESO DE EMPLEADOS");

        jButtonI.setFont(new java.awt.Font("HP Simplified Hans", 1, 14)); // NOI18N
        jButtonI.setText("INGRESO");
        jButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIActionPerformed(evt);
            }
        });

        jButtonM.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonM.setText("VENTA MAYOR");
        jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMActionPerformed(evt);
            }
        });

        jButtonME.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonME.setText("VENTA MENOR");
        jButtonME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMEActionPerformed(evt);
            }
        });

        jButtonBO.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonBO.setText("BORRAR");
        jButtonBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBOActionPerformed(evt);
            }
        });

        jButtonGT.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonGT.setText("GRAN TOTAL");
        jButtonGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGTActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre del Empleado");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Mes Enero");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Mes Febrero");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Mes Marzo");

        jTextArearespuesta.setColumns(20);
        jTextArearespuesta.setRows(5);
        jScrollPane1.setViewportView(jTextArearespuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBO)
                    .addComponent(jButtonME)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(jLabel5))
                                .addComponent(jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldE, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addComponent(jLabel3))
                                .addComponent(jTextFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonM)
                                        .addComponent(jButtonGT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonM)
                    .addComponent(jButtonME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGT)
                            .addComponent(jButtonBO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonI)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIActionPerformed
        USUARIOCONEXION USO = new USUARIOCONEXION();
        mdEMPLEADO EM =new mdEMPLEADO();
        Double EN=0.0,FE=0.0,MAR=0.0,VETOL=0.0,PRO=0.0;
        CONEXIONJDBC CO= new CONEXIONJDBC();
        mdEMPLEADO I= new mdEMPLEADO();
        I.setNombre(jTextFieldN.getText());
        EN=Double.parseDouble(jTextFieldE.getText());
        FE=Double.parseDouble(jTextFieldF.getText());
        MAR=Double.parseDouble(jTextFieldM.getText());
        VETOL=EN+FE+MAR;
        PRO=VETOL/3;
        I.setEnero(EN);
        I.setFebrero(FE);
        I.setMarzo(MAR);
        I.setVentasTotales(VETOL);
        I.setPromedio(PRO);
        CO.IngresarEmpleado(I);
    }//GEN-LAST:event_jButtonIActionPerformed

    private void jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMActionPerformed
        CONEXIONJDBC COM=new CONEXIONJDBC();
        String E="";
        String F="";
        String M="";
        E=COM.VentaMayor("Enero","max");
        F=COM.VentaMayor("Febrero","max");
        M=COM.VentaMayor("Marzo","max");
        String R="\n"+E+"\n"
              +"\n"+F+"\n"
              +"\n"+M;
        jTextArearespuesta.setText("resultado: " + R);
    }//GEN-LAST:event_jButtonMActionPerformed

    private void jButtonMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMEActionPerformed
        CONEXIONJDBC COM=new CONEXIONJDBC();
        String E="";
        String F="";
        String M="";
        E=COM.VentaMenor("Enero","min");
        F=COM.VentaMenor("Febrero","min");
        M=COM.VentaMenor("Marzo","min");
        String R="\n"+E+"\n"
              +"\n"+F+"\n"
              +"\n"+M;
        jTextArearespuesta.setText("resultado: " + R);
    }//GEN-LAST:event_jButtonMEActionPerformed

    private void jButtonBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBOActionPerformed
       jTextArearespuesta.setText("");
    }//GEN-LAST:event_jButtonBOActionPerformed

    private void jButtonGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGTActionPerformed
        CONEXIONJDBC COM=new CONEXIONJDBC();
        String tot="";
        tot=COM.VentaTotal("Total");
        jTextArearespuesta.setText("resultado:\n " + tot);
    }//GEN-LAST:event_jButtonGTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INGRESO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBO;
    private javax.swing.JButton jButtonGT;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArearespuesta;
    private javax.swing.JTextField jTextFieldE;
    private javax.swing.JTextField jTextFieldF;
    private javax.swing.JTextField jTextFieldM;
    private javax.swing.JTextField jTextFieldN;
    // End of variables declaration//GEN-END:variables
}
